name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r serpents_hand_toolkit/requirements.txt
        pip install flake8 black coverage sphinx
    - name: Lint with flake8
      run: |
        flake8 serpents_hand_toolkit/
    - name: Format with Black
      run: |
        black --check serpents_hand_toolkit/
    - name: Test with unittest and coverage
      run: |
        coverage run -m unittest discover -s tests
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
    - name: Build Sphinx documentation
      run: |
        cd docs
        make html